import type { Metadata } from "next";
import "./globals.css";

import { Instrument_Sans } from "next/font/google";

const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  variable: "--font-instrument-sans",
});
export const metadata: Metadata = {
  title: "Serge Soroka Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${instrumentSans.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col mx-5 my-13">{children}</body>
    </html>
  );
}
